# Use container-based infrastructure
sudo: false

language: scala

scala:
  - 2.10.5
  - 2.10.6
  - 2.11.7

jdk:
  - openjdk7
  - oraclejdk8

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/57534ac5b1f36eaa92c6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
